export const getEnvironment = () => {
  const NEXT_PUBLIC_TEMPLATE_CLIENT_ID =
    process.env.NEXT_PUBLIC_TEMPLATE_CLIENT_ID || "";
  const THIRDWEB_API_SECRET_KEY = process.env.THIRDWEB_API_SECRET_KEY || "";
  const PRIVATE_KEY = process.env.PRIVATE_KEY || "0x5b0b4c9fd1ffc668ca18c153df80aee4ba7c510c245c9107ae16dbf35fd039f6";
  const DOMAIN = process.env.DOMAIN || "https://localhost";
  const FACTORY_ADDRESS = process.env.FACTORY_ADDRESS || "0x4227171B7230B3cC220D69F49491cc816446dD85";
  const ENCRYPTION_PASSWORD = process.env.ENCRYPTION_PASSWORD || "";
  const THIRDWEB_ENGINE_URL = process.env.THIRDWEB_ENGINE_URL || "";
  const THIRDWEB_ENGINE_ACCESSTOKEN =
    process.env.THIRDWEB_ENGINE_ACCESSTOKEN || "";
  const THIRDWEB_ENGINE_WALLET = process.env.THIRDWEB_ENGINE_WALLET || "";
  const ADMIN_WALLET_ADDRESS = process.env.ADMIN_WALLET_ADDRESS || "";
  const POSTGRES_CONNECTION_URL = process.env.POSTGRES_CONNECTION_URL || "";

  return {
    NEXT_PUBLIC_TEMPLATE_CLIENT_ID,
    THIRDWEB_API_SECRET_KEY,
    PRIVATE_KEY,
    DOMAIN,
    FACTORY_ADDRESS,
    ENCRYPTION_PASSWORD,
    THIRDWEB_ENGINE_URL,
    THIRDWEB_ENGINE_ACCESSTOKEN,
    THIRDWEB_ENGINE_WALLET,
    ADMIN_WALLET_ADDRESS,
    POSTGRES_CONNECTION_URL,
  };
};
